import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import React from "react";
import Button from '@mui/material/Button';
import { inspect } from 'util';
import { DateTime } from "luxon";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]";
import UserInfoHelper from "@time-fit/helper/UserInfoHelper";
import FitbitAPIHelper from "@time-fit/data-source/fitbit/helper/FitbitAPIHelper";

export async function getServerSideProps(ctx) {
  const session = await getServerSession(ctx.req, ctx.res, authOptions);

  if (!session) {
    return {
      props: {},
    };
  }

  const user = await UserInfoHelper.getUserInfoByUsername(session.user.name);

  const targetDate = DateTime.fromISO("2022-03-10");

  const activityResult = await FitbitAPIHelper.getActvitySummaryAtDateForFitbitId(user.fitbitId, user.accessToken, targetDate)
    .then((responseData) => {
      console.log(
        `FitbitHelper.getActvitySummaryAtDateForFitbitId: ${JSON.stringify(
          responseData
        )}`
      );

      return {value: "success", data: responseData};
    })
    .catch((error) => {
      if (error.response) {
        // The request was made and the server responded with a status code
        // that falls out of the range of 2xx
        console.log(`Data: ${error.response.data}`);
        console.log(`Status: ${error.response.status}`);
        console.log(`StatusText: ${error.response.statusText}`);
        console.log(`Headers: ${error.response.headers}`);

        console.log(`Error response`);
        // which means, authentication falil
      } else if (error.request) {
        // The request was made but no response was received
        // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
        // http.ClientRequest in node.js
        console.log(error.request);

        console.log(`Error request`);
      } else {
        // Something happened in setting up the request that triggered an Error
        // console.log('Error', error.message);

        console.log("Error else");
      }
      //res.status(error.response.status).json({ response: inspect(error.response.data) });

      let resultObj = eval(`(${inspect(error.response.data)})`);
      return {value: "failed", data: resultObj};
    });


  return {
    props: { result: activityResult, dateString: targetDate.toISO()},
  };
}

export default function ActivitySummary({result, dateString}) {
  const { data: session, status } = useSession();
  const router = useRouter();

  if (status == "loading") return <div>loading...</div>;
  if (!session){
    router.push('/');
    return null;
  }


  let message = "";

  const briefDateString = dateString; //DateTime.fromISO(dateString).toISODate();

  if(result.value == "failed"){
    message = `Fail to get activity summary for ${briefDateString}!\n`;
  }
  else{
    message = `Succeed to get activity summary ${briefDateString}!\n`;
  }


  const resultData = result.data;

  const hasAuthorizationError = result.value == "failed" && resultData.errors[0].message.includes("Authorization Error");

  return (
    <div className={styles.container}>
      <Head>
        <title>Fitbit Break</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1 className={styles.title}>{message}</h1>
        <div>
            {result.value == "success"? <h2>Steps: {resultData.summary.steps}</h2>:null}
        </div>
        <div>
            {
                JSON.stringify(result.data)
            }
        </div>
        <div>
            {
                result.value == "failed"? `Error: ${resultData.errors[0]["errorType"]}`: null
            }
        </div>
        <div>
            {
                result.value == "failed" && resultData.errors[0]["errorType"] == "expired_token"? 
                
                <Button variant="contained" onClick={(event) => {
                  router.push("/refresh-token");
                  return;
                }} >Refresh token</Button>
                :null
            }
        </div>
        <br />
        <br />
        <div>
            {
                result.value == "failed" && resultData.errors[0]["errorType"] == "invalid_token"? <div>Please connect your Fitbit in Settings.</div>:null
            }
        </div>
        <br />
        <br />

        <Button variant="contained" onClick={(event) => {
            router.push("/main");
            return;
          }} >Return to home</Button>

      </main>

      <footer className={styles.main}>
        <div>Fitbit Break</div>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          
          <div>University of Michigan</div>
        </a>
      </footer>
    </div>
  );
}
